// CREATE BLOG
export const CREATE_BLOG_START = "CREATE_BLOG_START";
export const CREATE_BLOG_SUCCESS = "CREATE_BLOG_SUCCESS";

// LIKE BLOG
export const LIKE_BLOG_START = "LIKE_BLOG_START";
export const LIKE_BLOG_SUCCESS = "LIKE_BLOG_SUCCESS";

// GET ALL
export const GET_ALL_BLOGS_START = "GET_ALL_BLOGS_START";
export const GET_ALL_BLOGS_SUCCESS = "GET_ALL_BLOGS_SUCCESS";

// GET BY ID
export const GET_BLOGS_BY_ID_START = "GET_BLOGS_BY_ID_START";
export const GET_BLOGS_BY_ID_SUCCESS = "GET_BLOGS_BY_ID_SUCCESS";

// GET POPULAR
export const GET_BLOGS_POPULAR_START = "GET_BLOGS_POPULAR_START";
export const GET_BLOGS_POPULAR_SUCCESS = "GET_BLOGS_POPULAR_SUCCESS";

// UPDATE BLOG
export const UPDATE_BLOG_START = "UPDATE_BLOG_START";
export const UPDATE_BLOG_SUCCESS = "UPDATE_BLOG_SUCCESS";

// DELETE BLOG
export const DELETE_BLOG_START = "DELETE_BLOG_START";
export const DELETE_BLOG_SUCCESS = "DELETE_BLOG_SUCCESS";

// ADD FAVORITE BLOG
export const ADD_FAVORITE_BLOG = "ADD_FAVORITE_BLOG";