// CREATE 
export const CREATE_COMMENT_START = "CREATE_COMMENT_START";
export const CREATE_COMMENT_SUCCESS = "CREATE_COMMENT_SUCCESS";

// GET ALL
export const GET_ALL_COMMENT_START = "GET_ALL_COMMENT_START";
export const GET_ALL_COMMENT_SUCCESS = "GET_ALL_COMMENT_SUCCESS";

// UPDATE
export const UPDATE_COMMENT_START = "UPDATE_COMMENT_START";
export const UPDATE_COMMENT_SUCCESS = "UPDATE_COMMENT_SUCCESS";

// DELETE
export const DELETE_COMMENT_START = "DELETE_COMMENT_START";
export const DELETE_COMMENT_SUCCESS = "DELETE_COMMENT_SUCCESS";
